### ISSUE TITLE
Last version on Cocoapods

### ISSUE THREAD

**Issue by Nonouf** [shoheiyokoyama/Koyomi#10]
Just letting you know that the last version available on Cocoapods is still 0.1.0 (https://cocoapods.org/?q=koyomi). Would be great to push the last podspec if it's not an issue for you.

Thanks!

**Comment by shoheiyokoyama** [comment]
@Nonouf 
I forgot to push to Specs 😛 💦 .
I just push the latest podspec to Specs. [koyomi](https://cocoapods.org/?q=koyomi)
Thanks for letting me know. :laughing: :tada: :confetti_ball:
