### ISSUE TITLE
Enable to hide days of other months

### ISSUE THREAD

**Issue by OnlyMyRailgun** [shoheiyokoyama/Koyomi#14]
Do you have a plan to let it be able to hide days of other months in the future version?

**Comment by shoheiyokoyama** [comment]
@OnlyMyRailgun 
Hi Thank you for comment again :blush:
I have just finished to release version `1.0.4` and add `isHiddenOtherMonth`.
If you want to hide days of other months, set isHiddenOtherMonth to `true`

**Comment by OnlyMyRailgun** [comment]
@shoheiyokoyama Oh, my iOS master! Every feature is done so fast.
Thank you so much!

**Comment by shoheiyokoyama** [comment]
Thanks! :bowtie:
