### ISSUE TITLE
First day of week

### ISSUE THREAD

**Issue by vCrespoP** [shoheiyokoyama/Koyomi#15]
Any way of setting another day to be the first of the week? 

Thanks.

**Comment by shoheiyokoyama** [comment]
@vCrespoP  Hi.
Are you managing a date by `array`?
In that case, you should change order of it.

For example, `Koyomi` manage date in DateModel, and get first day of month in [indexAtBeginning](https://github.com/shoheiyokoyama/Koyomi/blob/master/Koyomi/DateModel.swift#L51-L57).

**Comment by EvilClay** [comment]
The question here is that the first column in your calendar is Sunday. But for some regions, weeks begin on Monday, so the fist column should be Monday for some states.

**Comment by EvilClay** [comment]
https://developer.apple.com/reference/foundation/nscalendar/1408310-firstweekday

**Comment by EvilClay** [comment]
..so can you expose the "fileprivate lazy var model: DateModel    = .init()" so we can access the model.calendar .. or make a method to allow to set a custom calnder into the model?

**Comment by shoheiyokoyama** [comment]
I support `holidayColor` for international calendar.
you want to change first week, set week.
Please wait until the next version.

```swift
// first of week is monday
koyomi.week = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN", ]
```

**Comment by lkuraer** [comment]
Hi, great library. But I can't change first day of week to Monday, it's still Sunday. How can I do that? Is there any method?
