### ISSUE TITLE
IB Designables Errors

### ISSUE THREAD

**Issue by christstuart** [shoheiyokoyama/Koyomi#16]
When I add the class to my collection view I get Failed to render and update auto layout status for my viewController. Also get Failed to update auto layout status: The agent crashed

**Comment by shoheiyokoyama** [comment]
@christstuart 
Thank you for letting me know IBDesignable Errors.
This problem has already been solved. so please wait for next version.

**Comment by shoheiyokoyama** [comment]
I have just finished to release version `1.1.0`.
Please update your Koyomi version :yum:

**Comment by haroldogtf** [comment]
This problem returned. I Cloud solve adding this to the end of my podfile:

```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end

```

**Comment by mohseen-headyio** [comment]
@haroldogtf Worked like a charm.
But will other pod frameworks will also be affected with this code ?
Could you please elaborate the code , I was unable to get it ?
thanks.
