### ISSUE TITLE
Saturday disappear in some width.

### ISSUE THREAD

**Issue by powhu** [shoheiyokoyama/Koyomi#19]
![](http://i.imgur.com/2wyMe8X.jpg)

You should floor cell width.

Great project Thank you.

**Comment by shoheiyokoyama** [comment]
@powhu 
Thank you for tell me bug.
What is the width disappearing saturday?

**Comment by iShavgula-TacTill** [comment]
Hello,
I'm having the same issue, with width equal to 375

**Comment by shoheiyokoyama** [comment]
@powhu @iShavgula-TacTill 

#23 

Thank you for sharing that with me :grin:
I resolved its bug and released version `1.2.4` :confetti_ball:
Update your Koyomi version.
