### ISSUE TITLE
swift3

### ISSUE THREAD

**Issue by shoheiyokoyama** [shoheiyokoyama/Koyomi#2]

**Comment by dkhamsing** [comment]
We would love to include this on awesome-ios after swift 3 support is added 
https://github.com/vsouza/awesome-ios/pull/1187

**Comment by shoheiyokoyama** [comment]
@dkhamsing
Thanks for contribution. [vsouza/awesome-ios#1187](https://github.com/vsouza/awesome-ios/pull/1187)
now, conversion to `Swift 3` including other task is in development.
Please wait a little longer :stuck_out_tongue_closed_eyes:

**Comment by devlove1C** [comment]
Can any one help me , how can i add magnifying glass in Calendar?
