### ISSUE TITLE
Next Month days

### ISSUE THREAD

**Issue by piv199** [shoheiyokoyama/Koyomi#26]
Currently calendar displays up to two weeks of the next month, and one for the past. How to make max 
one for the next month?

I don't want 6-12 week of the next month to be displayed. What should I do?

<img width="298" alt="screen shot 2017-02-19 at 00 52 59" src="https://cloud.githubusercontent.com/assets/8293191/23097490/d147c0b4-f63d-11e6-8207-047827adc0da.png">

**Comment by piv199** [comment]
Okay, I understood why it's needed :)

**Comment by viniciusvieir** [comment]
Can you please elaborate what it is needed? I'm facing the same issue

**Comment by piv199** [comment]
@viniciusvieir I've left as is, because it could feel all five rows, and adding/removing lines will be not looking good. So it's okay.

**Comment by lemarian** [comment]
Is there a way to hide the next and previous  month days?
